export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FECTH_INGREDIENTS_FAIL = 'FECTH_INGREDIENTS_FAIL';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FECTH_ORDERS_START = 'FECTH_ORDERS_START';
export const FECTH_ORDERS_SUCCESS = 'FECTH_ORDERS_SUCCESS';
export const FECTH_ORDERS_FAIL = 'FECTH_ORDERS_FAIL';